Fix basic grammatical issues in README.md
ValveSoftware/Proton pull request #1132
Opened 2018-09-01 15:00 UTC by LArrowHead

2018-09-05 15:15 UTC, aaronfranke requested changes

2018-09-05 15:15 UTC, aaronfranke commented on README.md
> +See the <tt>LICENSE</tt> files [here](https://github.com/ValveSoftware/Proton/blob/proton_3.7/LICENSE.proton), as well as the <tt>LICENSE</tt>, <tt>COPYING</tt>, etc files in each
This should be a [relative link](https://blog.github.com/2013-01-31-relative-links-in-markup-files/).

2018-09-05 15:28 UTC, LArrowHead commented
@aaronfranke That is the correct procedure for making it a relative link ?

2018-09-05 16:15 UTC, aaronfranke approved these changes

2018-09-06 19:31 UTC, aeikum commented
The grammar commit was merged as 27a83e3315f59f75595f19a751d7f9fab9630ac8. That LICENSE text is pointing readers to the sub-project LICENSEs, not Proton's LICENSE, so I didn't pick that commit.

2018-09-06 19:31 UTC, closed without merging