[MacOS] Add missing build dependency mingw-w64
ValveSoftware/Proton pull request #368
Opened 2018-08-24 08:36 UTC by tw1nk

mingw-w64 is needed for compiling dxvk

2018-08-26 11:57 UTC, cjwijtmans commented
this seems like a bad idea.

2018-08-27 17:11 UTC, kergoth commented
I think the better bet is just disable build_dxvk on mac, since (afaik) dxvk is useless on mac until it's able to link to MoltenVK. But this is absolutely needed to be able to build dxvk on mac, along with a few other fixes, and there's a meson bug preventing builds of dxvk 0.70 on mac right now as well.

2018-08-30 00:28 UTC, Tetramputechture requested changes
If this is added, use a comma instead of an extra 'and'

2018-08-30 00:28 UTC, Tetramputechture commented on README.md
> +well as cmake (for openal-soft), and mingw-w64 (for dxvk) and a recent nasm (for libjpeg-turbo), libtool, and automake. You can
Should be `well as cmake (for openal-soft), mingw-64 (for dxvk), and a recent nsam...`

2018-10-15 14:51 UTC, aeikum commented
The broken macos stuff has been removed, so this is no longer needed.

2018-10-15 14:51 UTC, closed without merging